service: serverless

provider:
  name: aws
  runtime: nodejs8.10
  profile: default
  region: us-east-2

plugins:
  - serverless-offline

functions:
  api:
    handler: sls-handler.fastifyApi
    events:
      - http: ANY /
          cors: true
      - http: 'ANY {proxy+}'
          cors: true
    environment:
      SECRET_ACCESS_TOKEN: ${ssm:SECRET_ACCESS_TOKEN}
